import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, addDoc, updateDoc, deleteDoc, collection, getDocs, query, where, orderBy, onSnapshot, serverTimestamp, increment } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { getStorage, ref, uploadBytesResumable, getDownloadURL } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js';
import { firebaseConfig, ADMIN_EMAILS } from './firebase-config.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const views=['authView','dashboardView','editorView','publicView'];
let app,auth,db,storage,currentUser=null,currentProfile=null,currentInvitationId=null,unsubscribeGuest=null,allInvitations=[],allUsers=[];
let state={}; let saveTimer;
const defaults={projectName:'Undangan Pernikahan',eventType:'Pernikahan',heroTitle:'The Wedding of',name1:'Alya',name2:'Fahri',introText:'Dengan memohon rahmat dan ridho Allah SWT, kami bermaksud mengundang Bapak/Ibu/Saudara/i untuk hadir pada acara bahagia kami.',eventDate:'2026-12-20',eventTime:'10:00',venue:'Gedung Serbaguna Bahagia',address:'Jl. Contoh No. 123, Kota Anda',mapsUrl:'',whatsapp:'',template:'emerald',accentColor:'#d4af37',titleFont:'serif',animations:true,showCountdown:true,cover:'',gallery:[],music:'',musicAutoplay:false,enableRsvp:true,enableGuestbook:true,enableGift:true,bankName:'BCA',bankNumber:'',bankHolder:'',qris:'',slug:'',guestLinkName:'',published:false,active:true,plan:'Pro',activeUntil:'',ownerId:'',ownerEmail:'',ownerName:'',visitCount:0};

function showView(id){views.forEach(v=>$('#'+v)?.classList.toggle('hidden',v!==id));$('#loadingScreen')?.classList.add('hidden');}
function toast(msg){const t=$('#toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}else alert(msg)}
function slugify(s){return String(s||'undangan').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)}
function cleanPhone(s){return String(s||'').replace(/\D/g,'').replace(/^0/,'62')}
function formatDate(v,long=false){if(!v)return '-';const d=new Date(v+'T00:00:00');return d.toLocaleDateString('id-ID',long?{weekday:'long',day:'numeric',month:'long',year:'numeric'}:{day:'numeric',month:'long',year:'numeric'})}
function configReady(){return firebaseConfig.apiKey && !firebaseConfig.apiKey.includes('GANTI_') && firebaseConfig.projectId && !firebaseConfig.projectId.includes('GANTI_')}
function isAdmin(){return currentProfile?.role==='admin' || ADMIN_EMAILS.map(x=>x.toLowerCase()).includes((currentUser?.email||'').toLowerCase())}
function activeByDate(inv){if(inv.active===false)return false;if(!inv.activeUntil)return true;return new Date(inv.activeUntil+'T23:59:59')>=new Date()}
function publicUrl(inv=state,guest=''){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('i',inv.id||currentInvitationId||inv.slug);if(guest)u.searchParams.set('to',guest);return u.toString()}

async function boot(){
 if(!configReady()){showView('authView');$('.auth-help').innerHTML='<strong>Firebase belum dikonfigurasi.</strong><br>Buka <code>firebase-config.js</code>, tempel konfigurasi Web App dari Firebase Console, lalu deploy ulang.';$$('#loginForm button,#registerForm button').forEach(b=>b.disabled=true);return}
 app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);storage=getStorage(app);
 const publicId=new URLSearchParams(location.search).get('i');
 if(publicId){await loadPublicInvitation(publicId);return}
 onAuthStateChanged(auth,async user=>{currentUser=user;if(!user){currentProfile=null;showView('authView');return}await ensureProfile(user);await showDashboard()});
}

async function ensureProfile(user){const r=doc(db,'users',user.uid);const snap=await getDoc(r);if(!snap.exists()){const role=ADMIN_EMAILS.map(x=>x.toLowerCase()).includes((user.email||'').toLowerCase())?'admin':'user';await setDoc(r,{name:user.displayName||user.email?.split('@')[0]||'User',email:user.email||'',role,plan:'Pro',active:true,createdAt:serverTimestamp()});currentProfile={name:user.displayName||user.email, email:user.email,role,plan:'Pro',active:true}}else currentProfile={id:snap.id,...snap.data()}}

$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('#loginEmail').value,$('#loginPassword').value)}catch(err){toast('Login gagal: '+friendlyError(err))}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();try{const cred=await createUserWithEmailAndPassword(auth,$('#registerEmail').value,$('#registerPassword').value);await setDoc(doc(db,'users',cred.user.uid),{name:$('#registerName').value.trim(),email:cred.user.email,role:'user',plan:'Pro',active:true,createdAt:serverTimestamp()});toast('Akun pelanggan berhasil dibuat')}catch(err){toast('Registrasi gagal: '+friendlyError(err))}};
$('#logoutBtn').onclick=()=>signOut(auth);
function friendlyError(e){const c=e?.code||'';if(c.includes('invalid-credential'))return 'email atau password salah';if(c.includes('email-already-in-use'))return 'email sudah terdaftar';if(c.includes('weak-password'))return 'password terlalu lemah';return e?.message?.replace('Firebase:','').slice(0,120)||'terjadi kesalahan'}

async function showDashboard(){showView('dashboardView');$('#userIdentity').textContent=currentProfile?.name||currentUser.email;$('#roleBadge').innerHTML=isAdmin()?'<span class="pill-admin">ADMIN</span>':'<span class="pill-user">PELANGGAN</span>';$('#adminStats').classList.toggle('hidden',!isAdmin());$('#adminUsers').classList.toggle('hidden',!isAdmin());await refreshDashboard()}
async function refreshDashboard(){
 const iq=isAdmin()?collection(db,'invitations'):query(collection(db,'invitations'),where('ownerId','==',currentUser.uid));
 const snap=await getDocs(iq);allInvitations=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));
 if(isAdmin()){const us=await getDocs(collection(db,'users'));allUsers=us.docs.map(d=>({id:d.id,...d.data()}));renderAdminStats();renderUsers()}
 renderInvitationCards();
}
function renderAdminStats(){ $('#statUsers').textContent=allUsers.filter(u=>u.role!=='admin').length;$('#statInvites').textContent=allInvitations.length;$('#statPublished').textContent=allInvitations.filter(x=>x.published&&activeByDate(x)).length;$('#statVisitors').textContent=allInvitations.reduce((n,x)=>n+(Number(x.visitCount)||0),0)}
function renderInvitationCards(){const box=$('#invitationCards'),term=$('#searchInvite').value.toLowerCase(),filter=$('#statusFilter').value;let rows=allInvitations.filter(x=>JSON.stringify([x.projectName,x.name1,x.name2,x.slug,x.ownerEmail]).toLowerCase().includes(term));rows=rows.filter(x=>filter==='all'||(filter==='published'&&x.published&&activeByDate(x))||(filter==='draft'&&!x.published)||(filter==='inactive'&&!activeByDate(x)));box.innerHTML='';if(!rows.length){box.innerHTML='<div class="empty-card">Belum ada undangan. Klik <b>+ Buat Undangan</b> untuk memulai.</div>';return}rows.forEach(inv=>{const c=document.createElement('article');c.className='invite-card';c.innerHTML=`<div class="invite-cover" style="${inv.cover?`background-image:url('${escapeAttr(inv.cover)}')`:''}"><span class="invite-status">${!activeByDate(inv)?'NONAKTIF':inv.published?'PUBLISHED':'DRAFT'}</span></div><div class="invite-body"><h3>${esc(inv.projectName||inv.name1+' & '+inv.name2)}</h3><p>${esc(inv.ownerEmail||'')} • ${esc(inv.plan||'Pro')}</p><div class="invite-meta"><span>${esc(inv.slug||'-')}</span><span>👁 ${Number(inv.visitCount)||0}</span></div><div class="invite-actions"><button class="btn primary" data-edit="${inv.id}">Edit</button><button class="btn secondary" data-open="${inv.id}">Lihat</button><button class="btn secondary" data-copy="${inv.id}">Link</button>${isAdmin()?`<button class="btn danger" data-del="${inv.id}">Hapus</button>`:''}</div></div>`;box.append(c)});box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>window.open(publicUrl({id:b.dataset.open}),'_blank'));box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(publicUrl({id:b.dataset.copy})).then(()=>toast('Link disalin')));box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteInvite(b.dataset.del))}
function renderUsers(){const box=$('#usersTable');box.innerHTML='<div class="user-row"><b>Nama</b><b>Email</b><b>Role</b><b>Paket</b><b>Status</b></div>';allUsers.forEach(u=>{const r=document.createElement('div');r.className='user-row';r.innerHTML=`<span>${esc(u.name||'-')}</span><span>${esc(u.email||'-')}</span><select data-role="${u.id}"><option ${u.role==='user'?'selected':''}>user</option><option ${u.role==='admin'?'selected':''}>admin</option></select><select data-plan="${u.id}"><option ${u.plan==='Basic'?'selected':''}>Basic</option><option ${u.plan==='Pro'?'selected':''}>Pro</option><option ${u.plan==='Premium'?'selected':''}>Premium</option></select><button class="btn secondary" data-active-user="${u.id}">${u.active===false?'Aktifkan':'Nonaktifkan'}</button>`;box.append(r)});box.querySelectorAll('[data-role]').forEach(s=>s.onchange=()=>updateDoc(doc(db,'users',s.dataset.role),{role:s.value}).then(refreshDashboard));box.querySelectorAll('[data-plan]').forEach(s=>s.onchange=()=>updateDoc(doc(db,'users',s.dataset.plan),{plan:s.value}).then(refreshDashboard));box.querySelectorAll('[data-active-user]').forEach(b=>b.onclick=async()=>{const u=allUsers.find(x=>x.id===b.dataset.activeUser);await updateDoc(doc(db,'users',u.id),{active:u.active===false});refreshDashboard()})}
$('#searchInvite').oninput=renderInvitationCards;$('#statusFilter').onchange=renderInvitationCards;
$('#createInvitationBtn').onclick=()=>openEditor(null);
async function deleteInvite(id){if(!confirm('Hapus undangan ini? Data Firestore akan dihapus.'))return;await deleteDoc(doc(db,'invitations',id));toast('Undangan dihapus');refreshDashboard()}

async function openEditor(id){
 currentInvitationId=id; if(unsubscribeGuest){unsubscribeGuest();unsubscribeGuest=null}
 if(id){const s=await getDoc(doc(db,'invitations',id));if(!s.exists())return toast('Undangan tidak ditemukan');state={...defaults,id:s.id,...s.data()}}else{state={...defaults,slug:'',ownerId:currentUser.uid,ownerEmail:currentUser.email,ownerName:currentProfile?.name||'',plan:currentProfile?.plan||'Pro',active:true,published:false};state.slug=slugify(state.name1+'-'+state.name2+'-'+Date.now().toString().slice(-4))}
 bindStateToInputs();render();$('#adminPublishControls').classList.toggle('hidden',!isAdmin());$('#editorOwner').textContent=isAdmin()?`Owner: ${state.ownerEmail||currentUser.email}`:'Firebase Cloud';showView('editorView');listenGuestStats();
}
function bindStateToInputs(){const ids=['projectName','eventType','heroTitle','name1','name2','introText','eventDate','eventTime','venue','address','mapsUrl','whatsapp','accentColor','titleFont','bankName','bankNumber','bankHolder','slug','guestLinkName','plan','activeUntil'];ids.forEach(id=>{if($('#'+id))$('#'+id).value=state[id]??''});['animations','showCountdown','musicAutoplay','enableRsvp','enableGuestbook','enableGift','published','active'].forEach(id=>{if($('#'+id))$('#'+id).checked=state[id]!==false});$$('.template').forEach(b=>b.classList.toggle('active',b.dataset.template===state.template));$('#packageLabel').textContent=state.plan||'Pro'}
function capture(){const ids=['projectName','eventType','heroTitle','name1','name2','introText','eventDate','eventTime','venue','address','mapsUrl','whatsapp','accentColor','titleFont','bankName','bankNumber','bankHolder','slug','guestLinkName','plan','activeUntil'];ids.forEach(id=>{if($('#'+id))state[id]=$('#'+id).value});['animations','showCountdown','musicAutoplay','enableRsvp','enableGuestbook','enableGift','published','active'].forEach(id=>{if($('#'+id))state[id]=$('#'+id).checked});render();$('#saveState').textContent='Ada perubahan';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(currentInvitationId)saveInvitation(true)},1500)}
function render(){
 const text={pHeroTitle:state.heroTitle,pName1:state.name1,pName2:state.name2,pDateHero:formatDate(state.eventDate),pEventType:state.eventType,pEventHeading:state.eventType,pIntroText:state.introText,pCoupleNames:`${state.name1} & ${state.name2}`,pClosingNames:`${state.name1} & ${state.name2}`,pFullDate:formatDate(state.eventDate,true),pTime:(state.eventTime||'--:--').replace(':','.')+' WIB',pVenue:state.venue,pAddress:state.address,pBankName:state.bankName,pBankNumber:state.bankNumber,pBankHolder:state.bankHolder};Object.entries(text).forEach(([id,val])=>{if($('#'+id))$('#'+id).textContent=val||''});
 $('#mapsBtn').href=state.mapsUrl||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(state.address||'')}`;$('#waBtn').href=`https://wa.me/${cleanPhone(state.whatsapp)}?text=${encodeURIComponent(`Halo, saya ingin konfirmasi kehadiran untuk undangan ${state.name1} & ${state.name2}.`)}`;$('#giftSection').classList.toggle('hidden',!state.enableGift);$('#rsvpSection').classList.toggle('hidden',!state.enableRsvp);$('#guestbookSection').classList.toggle('hidden',!state.enableGuestbook);$('#countdownSection').classList.toggle('hidden',!state.showCountdown);const inv=$('#invitation');inv.className=`invitation theme-${state.template||'emerald'}`+(state.animations?'':' no-animation')+(state.titleFont==='sans'?' sans-title':'');inv.style.setProperty('--accent',state.accentColor||'#d4af37');if(state.cover){$('#coverCircle').style.backgroundImage=`url(${state.cover})`;$('#heroSection').style.backgroundImage=`linear-gradient(rgba(10,20,15,.52),rgba(10,20,15,.72)),url(${state.cover})`;$('#heroSection').style.backgroundSize='cover';$('#heroSection').style.backgroundPosition='center'}else{$('#coverCircle').style.backgroundImage='';$('#heroSection').style.backgroundImage=''}renderGallery();if(state.qris){$('#qrisPreview').src=state.qris;$('#qrisPreview').classList.remove('hidden')}else $('#qrisPreview').classList.add('hidden');const a=$('#bgMusic');if(state.music){a.src=state.music;$('#musicFab').classList.remove('hidden')}else $('#musicFab').classList.add('hidden');$('#shareUrl').value=publicUrl(state,state.guestLinkName?.trim()||'');$('#packageLabel').textContent=state.plan||'Pro';applyGuestFromUrl();updateCountdown();
}
function renderGallery(){const g=$('#photoGrid'),m=$('#galleryManager');g.innerHTML='';m.innerHTML='';(state.gallery||[]).forEach((src,i)=>{const img=new Image();img.src=src;img.alt='Galeri';g.append(img);const w=document.createElement('div');w.style.position='relative';const mi=img.cloneNode();w.append(mi);w.title='Klik untuk menghapus';w.onclick=()=>{state.gallery.splice(i,1);render();capture()};m.append(w)});if(!(state.gallery||[]).length){['Foto 1','Foto 2','Foto 3'].forEach(t=>{const d=document.createElement('div');d.className='photo-placeholder';d.textContent=t;g.append(d)})}}
async function saveInvitation(silent=false){if(!currentUser)return;if(!state.slug)state.slug=slugify(`${state.name1}-${state.name2}`);const payload={...state,ownerId:state.ownerId||currentUser.uid,ownerEmail:state.ownerEmail||currentUser.email,ownerName:state.ownerName||currentProfile?.name||'',updatedAt:serverTimestamp()};delete payload.id;if(!currentInvitationId){payload.createdAt=serverTimestamp();const r=await addDoc(collection(db,'invitations'),payload);currentInvitationId=r.id;state.id=r.id}else await updateDoc(doc(db,'invitations',currentInvitationId),payload);$('#saveState').textContent='Tersimpan di Firebase';if(!silent)toast('Tersimpan ke Firebase');render()}
$('#saveCloud').onclick=()=>saveInvitation(false);$('#backDashboard').onclick=()=>showDashboard();$('#openInvitation').onclick=async()=>{if(!currentInvitationId)await saveInvitation(true);window.open(publicUrl(state,state.guestLinkName?.trim()||''),'_blank')};$('#copyShare').onclick=()=>navigator.clipboard.writeText($('#shareUrl').value).then(()=>toast('Link undangan disalin'));

$$('input:not([type=file]),textarea,select').forEach(el=>el.addEventListener('input',()=>{if(!$('#editorView').classList.contains('hidden'))capture()}));$$('input[type=checkbox]').forEach(el=>el.addEventListener('change',()=>{if(!$('#editorView').classList.contains('hidden'))capture()}));$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(`[data-panel="${btn.dataset.tab}"]`).classList.add('active')});$$('.template').forEach(btn=>btn.onclick=()=>{state.template=btn.dataset.template;$$('.template').forEach(x=>x.classList.remove('active'));btn.classList.add('active');capture()});$$('.view-switch button').forEach(btn=>btn.onclick=()=>{$$('.view-switch button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('#device').className='device '+btn.dataset.view});$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#scrollOpen').onclick=()=>$('#contentStart').scrollIntoView({behavior:'smooth'});$('#copyBank').onclick=()=>navigator.clipboard.writeText(state.bankNumber||'').then(()=>toast('Nomor rekening disalin'));$('#musicFab').onclick=async()=>{const a=$('#bgMusic');if(a.paused){try{await a.play();$('#musicFab').textContent='❚❚'}catch(e){toast('Klik lagi untuk memutar musik')}}else{a.pause();$('#musicFab').textContent='♫'}};

async function uploadFile(file,kind){if(!currentUser)throw new Error('Harus login');if(!currentInvitationId)await saveInvitation(true);const path=`users/${state.ownerId||currentUser.uid}/invitations/${currentInvitationId}/${kind}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const task=uploadBytesResumable(ref(storage,path),file);$('#uploadProgress').classList.remove('hidden');return new Promise((resolve,reject)=>task.on('state_changed',s=>{$('#uploadProgress').textContent=`Upload ${kind}: ${Math.round(s.bytesTransferred/s.totalBytes*100)}%`},reject,async()=>{const url=await getDownloadURL(task.snapshot.ref);$('#uploadProgress').classList.add('hidden');resolve(url)}))}
$('#coverUpload').onchange=async e=>{if(e.target.files[0]){state.cover=await uploadFile(e.target.files[0],'cover');render();await saveInvitation(true)}};$('#galleryUpload').onchange=async e=>{for(const f of [...e.target.files].slice(0,12)){state.gallery=state.gallery||[];state.gallery.push(await uploadFile(f,'gallery'))}render();await saveInvitation(true)};$('#qrisUpload').onchange=async e=>{if(e.target.files[0]){state.qris=await uploadFile(e.target.files[0],'qris');render();await saveInvitation(true)}};$('#musicUpload').onchange=async e=>{if(e.target.files[0]){state.music=await uploadFile(e.target.files[0],'music');render();await saveInvitation(true)}};

function listenGuestStats(){if(!currentInvitationId)return;let rsvp=[];onSnapshot(collection(db,'invitations',currentInvitationId,'rsvps'),s=>{rsvp=s.docs.map(d=>d.data());$('#rsvpYes').textContent=rsvp.filter(x=>x.status==='yes').reduce((n,x)=>n+(Number(x.pax)||1),0);$('#rsvpNo').textContent=rsvp.filter(x=>x.status==='no').length;$('#uniqueGuestCount').textContent=rsvp.length});unsubscribeGuest=onSnapshot(query(collection(db,'invitations',currentInvitationId,'guestbook'),orderBy('createdAt','desc')),s=>{$('#guestCount').textContent=s.size;renderGuestList(s.docs.map(d=>d.data()))});$('#visitCount').textContent=Number(state.visitCount)||0}
function renderGuestList(rows){const list=$('#guestList');list.innerHTML='';rows.slice(0,20).forEach(x=>{const i=document.createElement('div');i.className='guest-item';i.innerHTML=`<strong>${esc(x.name||'Tamu')}</strong><p>${esc(x.message||'')}</p>`;list.append(i)})}
$('#rsvpForm').onsubmit=async e=>{e.preventDefault();if(!currentInvitationId)return;try{await addDoc(collection(db,'invitations',currentInvitationId,'rsvps'),{name:$('#rsvpName').value.trim(),status:$('#rsvpStatus').value,pax:Number($('#rsvpPax').value)||1,createdAt:serverTimestamp()});toast('Konfirmasi kehadiran terkirim');$('#rsvpPax').value=1}catch(err){toast('RSVP gagal dikirim')}};$('#guestbookForm').onsubmit=async e=>{e.preventDefault();if(!currentInvitationId)return;try{await addDoc(collection(db,'invitations',currentInvitationId,'guestbook'),{name:$('#guestbookName').value.trim(),message:$('#guestbookMessage').value.trim(),createdAt:serverTimestamp()});toast('Ucapan terkirim');$('#guestbookMessage').value=''}catch(err){toast('Ucapan gagal dikirim')}};

async function loadPublicInvitation(idOrSlug){
 try{let snap=await getDoc(doc(db,'invitations',idOrSlug));if(!snap.exists()){const q=query(collection(db,'invitations'),where('slug','==',idOrSlug));const qs=await getDocs(q);if(qs.empty)throw new Error('not-found');snap=qs.docs[0]}state={...defaults,id:snap.id,...snap.data()};currentInvitationId=snap.id;if(!state.published||!activeByDate(state)){document.body.innerHTML='<div class="inactive-notice"><div><h1>Undangan tidak aktif</h1><p>Undangan ini belum dipublikasikan atau masa aktifnya telah berakhir.</p></div></div>';return}document.body.classList.add('public-mode');showView('editorView');$('#sidebar').classList.add('hidden');$('.topbar').classList.add('hidden');$('.main-stage').style.margin='0';$('.preview-zone').style.padding='0';$('#device').className='device desktop';bindStateToInputs();render();recordVisit();unsubscribeGuest=onSnapshot(query(collection(db,'invitations',currentInvitationId,'guestbook'),orderBy('createdAt','desc')),s=>renderGuestList(s.docs.map(d=>d.data())));if(state.music&&state.musicAutoplay){document.addEventListener('click',()=>$('#bgMusic').play().catch(()=>{}),{once:true})}
 }catch(e){document.body.innerHTML='<div class="inactive-notice"><div><h1>Undangan tidak ditemukan</h1><p>Periksa kembali link undangan yang Anda buka.</p></div></div>'}
}
async function recordVisit(){try{const sid=sessionStorage.getItem('adit_visit_'+currentInvitationId);if(sid)return;sessionStorage.setItem('adit_visit_'+currentInvitationId,'1');await addDoc(collection(db,'invitations',currentInvitationId,'visits'),{at:serverTimestamp(),guest:new URLSearchParams(location.search).get('to')||''});await updateDoc(doc(db,'invitations',currentInvitationId),{visitCount:increment(1)})}catch(e){}}
function applyGuestFromUrl(){const to=new URLSearchParams(location.search).get('to');$('#pGuestName').textContent=to||'Bapak/Ibu/Saudara/i';if(to){$('#rsvpName').value=to;$('#guestbookName').value=to}}
function updateCountdown(){if(!state.eventDate)return;const target=new Date(`${state.eventDate}T${state.eventTime||'00:00'}:00`).getTime();let diff=Math.max(0,target-Date.now());const d=Math.floor(diff/86400000);diff%=86400000;const h=Math.floor(diff/3600000);diff%=3600000;const m=Math.floor(diff/60000),s=Math.floor((diff%60000)/1000);if($('#cdDays')){$('#cdDays').textContent=String(d).padStart(3,'0');$('#cdHours').textContent=String(h).padStart(2,'0');$('#cdMinutes').textContent=String(m).padStart(2,'0');$('#cdSeconds').textContent=String(s).padStart(2,'0')}}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function escapeAttr(s){return String(s||'').replace(/'/g,'%27')}
setInterval(updateCountdown,1000);boot();
