import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SUPABASE_URL, SUPABASE_ANON_KEY, ADMIN_EMAILS, STORAGE_BUCKET } from './supabase-config.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const views=['authView','dashboardView','editorView','publicView'];
let supabase,currentUser=null,currentProfile=null,currentInvitationId=null,unsubscribeGuest=null,allInvitations=[],allUsers=[];
let state={}; let saveTimer;
const defaults={projectName:'Undangan Pernikahan',eventType:'Pernikahan',heroTitle:'The Wedding of',name1:'Alya',name2:'Fahri',introText:'Dengan memohon rahmat dan ridho Allah SWT, kami bermaksud mengundang Bapak/Ibu/Saudara/i untuk hadir pada acara bahagia kami.',eventDate:'2026-12-20',eventTime:'10:00',venue:'Gedung Serbaguna Bahagia',address:'Jl. Contoh No. 123, Kota Anda',mapsUrl:'',whatsapp:'',template:'emerald',accentColor:'#d4af37',titleFont:'serif',animations:true,showCountdown:true,cover:'',gallery:[],music:'',musicAutoplay:false,enableRsvp:true,enableGuestbook:true,enableGift:true,bankName:'BCA',bankNumber:'',bankHolder:'',qris:'',slug:'',guestLinkName:'',published:false,active:true,plan:'Pro',activeUntil:'',ownerId:'',ownerEmail:'',ownerName:'',visitCount:0};

function showView(id){views.forEach(v=>$('#'+v)?.classList.toggle('hidden',v!==id));$('#loadingScreen')?.classList.add('hidden');}
function toast(msg){const t=$('#toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}else alert(msg)}
function slugify(s){return String(s||'undangan').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)}
function cleanPhone(s){return String(s||'').replace(/\D/g,'').replace(/^0/,'62')}
function formatDate(v,long=false){if(!v)return '-';const d=new Date(v+'T00:00:00');return d.toLocaleDateString('id-ID',long?{weekday:'long',day:'numeric',month:'long',year:'numeric'}:{day:'numeric',month:'long',year:'numeric'})}
function configReady(){return SUPABASE_URL && !SUPABASE_URL.includes('GANTI_') && SUPABASE_ANON_KEY && !SUPABASE_ANON_KEY.includes('GANTI_')}
function isAdmin(){return currentProfile?.role==='admin' || ADMIN_EMAILS.map(x=>x.toLowerCase()).includes((currentUser?.email||'').toLowerCase())}
function activeByDate(inv){if(inv.active===false)return false;if(!inv.activeUntil)return true;return new Date(inv.activeUntil+'T23:59:59')>=new Date()}
function publicUrl(inv=state,guest=''){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('i',inv.id||currentInvitationId||inv.slug);if(guest)u.searchParams.set('to',guest);return u.toString()}

async function boot(){
 if(!configReady()){showView('authView');$('.auth-help').innerHTML='<strong>Supabase belum dikonfigurasi.</strong><br>Buka <code>supabase-config.js</code>, isi Project URL dan anon key dari Supabase Dashboard, lalu deploy ulang.';$$('#loginForm button,#registerForm button').forEach(b=>b.disabled=true);return}
 supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
 const publicId=new URLSearchParams(location.search).get('i');
 if(publicId){await loadPublicInvitation(publicId);return}
 const {data:{session}}=await supabase.auth.getSession();
 await handleSession(session);
 supabase.auth.onAuthStateChange(async(_event,session)=>{await handleSession(session)});
}
async function handleSession(session){
 currentUser=session?.user||null;
 if(!currentUser){currentProfile=null;showView('authView');return}
 await ensureProfile(currentUser);await showDashboard();
}
async function ensureProfile(user){
 let {data,error}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();
 if(error)throw error;
 if(!data){
  const role=ADMIN_EMAILS.map(x=>x.toLowerCase()).includes((user.email||'').toLowerCase())?'admin':'user';
  const profile={id:user.id,name:user.user_metadata?.name||user.email?.split('@')[0]||'User',email:user.email||'',role,plan:'Pro',active:true};
  const r=await supabase.from('profiles').upsert(profile).select().single(); if(r.error)throw r.error; data=r.data;
 }
 currentProfile=data;
}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const {error}=await supabase.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value});if(error)throw error}catch(err){toast('Login gagal: '+friendlyError(err))}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();try{const {data,error}=await supabase.auth.signUp({email:$('#registerEmail').value,password:$('#registerPassword').value,options:{data:{name:$('#registerName').value.trim()}}});if(error)throw error;toast(data.session?'Akun pelanggan berhasil dibuat':'Akun dibuat. Jika konfirmasi email aktif, silakan cek email lalu login.')}catch(err){toast('Registrasi gagal: '+friendlyError(err))}};
$('#logoutBtn').onclick=()=>supabase.auth.signOut();
function friendlyError(e){const m=(e?.message||'').toLowerCase();if(m.includes('invalid login credentials'))return 'email atau password salah';if(m.includes('already registered'))return 'email sudah terdaftar';if(m.includes('password'))return e.message;return e?.message?.slice(0,140)||'terjadi kesalahan'}

function invitationFromRow(r){return {...defaults,...(r.data||{}),id:r.id,ownerId:r.owner_id,ownerEmail:r.owner_email,ownerName:r.owner_name,slug:r.slug,projectName:r.project_name,plan:r.plan,published:r.published,active:r.active,activeUntil:r.active_until||'',visitCount:Number(r.visit_count)||0,createdAt:r.created_at,updatedAt:r.updated_at}}
function invitationToRow(v){const data={...v};delete data.id;delete data.createdAt;delete data.updatedAt;return {owner_id:v.ownerId||currentUser.id,owner_email:v.ownerEmail||currentUser.email||'',owner_name:v.ownerName||currentProfile?.name||'',slug:v.slug,project_name:v.projectName||'Undangan Pernikahan',plan:v.plan||'Pro',published:!!v.published,active:v.active!==false,active_until:v.activeUntil||null,visit_count:Number(v.visitCount)||0,data}}
async function showDashboard(){showView('dashboardView');$('#userIdentity').textContent=currentProfile?.name||currentUser.email;$('#roleBadge').innerHTML=isAdmin()?'<span class="pill-admin">ADMIN</span>':'<span class="pill-user">PELANGGAN</span>';$('#adminStats').classList.toggle('hidden',!isAdmin());$('#adminUsers').classList.toggle('hidden',!isAdmin());await refreshDashboard()}
async function refreshDashboard(){
 let q=supabase.from('invitations').select('*').order('updated_at',{ascending:false});
 if(!isAdmin())q=q.eq('owner_id',currentUser.id);
 const {data,error}=await q;if(error){toast('Gagal memuat undangan: '+friendlyError(error));return}
 allInvitations=(data||[]).map(invitationFromRow);
 if(isAdmin()){const u=await supabase.from('profiles').select('*').order('created_at',{ascending:false});if(u.error)toast('Gagal memuat user: '+friendlyError(u.error));else{allUsers=u.data||[];renderAdminStats();renderUsers()}}
 renderInvitationCards();
}
function renderAdminStats(){ $('#statUsers').textContent=allUsers.filter(u=>u.role!=='admin').length;$('#statInvites').textContent=allInvitations.length;$('#statPublished').textContent=allInvitations.filter(x=>x.published&&activeByDate(x)).length;$('#statVisitors').textContent=allInvitations.reduce((n,x)=>n+(Number(x.visitCount)||0),0)}
function renderInvitationCards(){const box=$('#invitationCards'),term=$('#searchInvite').value.toLowerCase(),filter=$('#statusFilter').value;let rows=allInvitations.filter(x=>JSON.stringify([x.projectName,x.name1,x.name2,x.slug,x.ownerEmail]).toLowerCase().includes(term));rows=rows.filter(x=>filter==='all'||(filter==='published'&&x.published&&activeByDate(x))||(filter==='draft'&&!x.published)||(filter==='inactive'&&!activeByDate(x)));box.innerHTML='';if(!rows.length){box.innerHTML='<div class="empty-card">Belum ada undangan. Klik <b>+ Buat Undangan</b> untuk memulai.</div>';return}rows.forEach(inv=>{const c=document.createElement('article');c.className='invite-card';c.innerHTML=`<div class="invite-cover" style="${inv.cover?`background-image:url('${escapeAttr(inv.cover)}')`:''}"><span class="invite-status">${!activeByDate(inv)?'NONAKTIF':inv.published?'PUBLISHED':'DRAFT'}</span></div><div class="invite-body"><h3>${esc(inv.projectName||inv.name1+' & '+inv.name2)}</h3><p>${esc(inv.ownerEmail||'')} • ${esc(inv.plan||'Pro')}</p><div class="invite-meta"><span>${esc(inv.slug||'-')}</span><span>👁 ${Number(inv.visitCount)||0}</span></div><div class="invite-actions"><button class="btn primary" data-edit="${inv.id}">Edit</button><button class="btn secondary" data-open="${inv.id}">Lihat</button><button class="btn secondary" data-copy="${inv.id}">Link</button>${isAdmin()?`<button class="btn danger" data-del="${inv.id}">Hapus</button>`:''}</div></div>`;box.append(c)});box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>window.open(publicUrl({id:b.dataset.open}),'_blank'));box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(publicUrl({id:b.dataset.copy})).then(()=>toast('Link disalin')));box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteInvite(b.dataset.del))}
function renderUsers(){const box=$('#usersTable');box.innerHTML='<div class="user-row"><b>Nama</b><b>Email</b><b>Role</b><b>Paket</b><b>Status</b></div>';allUsers.forEach(u=>{const r=document.createElement('div');r.className='user-row';r.innerHTML=`<span>${esc(u.name||'-')}</span><span>${esc(u.email||'-')}</span><select data-role="${u.id}"><option ${u.role==='user'?'selected':''}>user</option><option ${u.role==='admin'?'selected':''}>admin</option></select><select data-plan="${u.id}"><option ${u.plan==='Basic'?'selected':''}>Basic</option><option ${u.plan==='Pro'?'selected':''}>Pro</option><option ${u.plan==='Premium'?'selected':''}>Premium</option></select><button class="btn secondary" data-active-user="${u.id}">${u.active===false?'Aktifkan':'Nonaktifkan'}</button>`;box.append(r)});box.querySelectorAll('[data-role]').forEach(el=>el.onchange=async()=>{const {error}=await supabase.from('profiles').update({role:el.value,updated_at:new Date().toISOString()}).eq('id',el.dataset.role);if(error)toast('Gagal: '+friendlyError(error));else refreshDashboard()});box.querySelectorAll('[data-plan]').forEach(el=>el.onchange=async()=>{const {error}=await supabase.from('profiles').update({plan:el.value,updated_at:new Date().toISOString()}).eq('id',el.dataset.plan);if(error)toast('Gagal: '+friendlyError(error));else refreshDashboard()});box.querySelectorAll('[data-active-user]').forEach(b=>b.onclick=async()=>{const u=allUsers.find(x=>x.id===b.dataset.activeUser);const {error}=await supabase.from('profiles').update({active:u.active===false,updated_at:new Date().toISOString()}).eq('id',u.id);if(error)toast('Gagal: '+friendlyError(error));else refreshDashboard()})}
$('#searchInvite').oninput=renderInvitationCards;$('#statusFilter').onchange=renderInvitationCards;
$('#createInvitationBtn').onclick=()=>openEditor(null);
async function deleteInvite(id){if(!confirm('Hapus undangan ini? Data Supabase akan dihapus.'))return;const {error}=await supabase.from('invitations').delete().eq('id',id);if(error)return toast('Gagal menghapus: '+friendlyError(error));toast('Undangan dihapus');refreshDashboard()}

async function openEditor(id){
 currentInvitationId=id; if(unsubscribeGuest){stopGuestRealtime()}
 if(id){const {data,error}=await supabase.from('invitations').select('*').eq('id',id).single();if(error||!data)return toast('Undangan tidak ditemukan');state=invitationFromRow(data)}else{state={...defaults,slug:'',ownerId:currentUser.id,ownerEmail:currentUser.email,ownerName:currentProfile?.name||'',plan:currentProfile?.plan||'Pro',active:true,published:false};state.slug=slugify(state.name1+'-'+state.name2+'-'+Date.now().toString().slice(-4))}
 bindStateToInputs();render();$('#adminPublishControls').classList.toggle('hidden',!isAdmin());$('#editorOwner').textContent=isAdmin()?`Owner: ${state.ownerEmail||currentUser.email}`:'Supabase Cloud';showView('editorView');listenGuestStats();
}
function bindStateToInputs(){const ids=['projectName','eventType','heroTitle','name1','name2','introText','eventDate','eventTime','venue','address','mapsUrl','whatsapp','accentColor','titleFont','bankName','bankNumber','bankHolder','slug','guestLinkName','plan','activeUntil'];ids.forEach(id=>{if($('#'+id))$('#'+id).value=state[id]??''});['animations','showCountdown','musicAutoplay','enableRsvp','enableGuestbook','enableGift','published','active'].forEach(id=>{if($('#'+id))$('#'+id).checked=state[id]!==false});$$('.template').forEach(b=>b.classList.toggle('active',b.dataset.template===state.template));$('#packageLabel').textContent=state.plan||'Pro'}
function capture(){const ids=['projectName','eventType','heroTitle','name1','name2','introText','eventDate','eventTime','venue','address','mapsUrl','whatsapp','accentColor','titleFont','bankName','bankNumber','bankHolder','slug','guestLinkName','plan','activeUntil'];ids.forEach(id=>{if($('#'+id))state[id]=$('#'+id).value});['animations','showCountdown','musicAutoplay','enableRsvp','enableGuestbook','enableGift','published','active'].forEach(id=>{if($('#'+id))state[id]=$('#'+id).checked});render();$('#saveState').textContent='Ada perubahan';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(currentInvitationId)saveInvitation(true)},1500)}
function render(){
 const text={pHeroTitle:state.heroTitle,pName1:state.name1,pName2:state.name2,pDateHero:formatDate(state.eventDate),pEventType:state.eventType,pEventHeading:state.eventType,pIntroText:state.introText,pCoupleNames:`${state.name1} & ${state.name2}`,pClosingNames:`${state.name1} & ${state.name2}`,pFullDate:formatDate(state.eventDate,true),pTime:(state.eventTime||'--:--').replace(':','.')+' WIB',pVenue:state.venue,pAddress:state.address,pBankName:state.bankName,pBankNumber:state.bankNumber,pBankHolder:state.bankHolder};Object.entries(text).forEach(([id,val])=>{if($('#'+id))$('#'+id).textContent=val||''});
 $('#mapsBtn').href=state.mapsUrl||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(state.address||'')}`;$('#waBtn').href=`https://wa.me/${cleanPhone(state.whatsapp)}?text=${encodeURIComponent(`Halo, saya ingin konfirmasi kehadiran untuk undangan ${state.name1} & ${state.name2}.`)}`;$('#giftSection').classList.toggle('hidden',!state.enableGift);$('#rsvpSection').classList.toggle('hidden',!state.enableRsvp);$('#guestbookSection').classList.toggle('hidden',!state.enableGuestbook);$('#countdownSection').classList.toggle('hidden',!state.showCountdown);const inv=$('#invitation');inv.className=`invitation theme-${state.template||'emerald'}`+(state.animations?'':' no-animation')+(state.titleFont==='sans'?' sans-title':'');inv.style.setProperty('--accent',state.accentColor||'#d4af37');if(state.cover){$('#coverCircle').style.backgroundImage=`url(${state.cover})`;$('#heroSection').style.backgroundImage=`linear-gradient(rgba(10,20,15,.52),rgba(10,20,15,.72)),url(${state.cover})`;$('#heroSection').style.backgroundSize='cover';$('#heroSection').style.backgroundPosition='center'}else{$('#coverCircle').style.backgroundImage='';$('#heroSection').style.backgroundImage=''}renderGallery();if(state.qris){$('#qrisPreview').src=state.qris;$('#qrisPreview').classList.remove('hidden')}else $('#qrisPreview').classList.add('hidden');const a=$('#bgMusic');if(state.music){a.src=state.music;$('#musicFab').classList.remove('hidden')}else $('#musicFab').classList.add('hidden');$('#shareUrl').value=publicUrl(state,state.guestLinkName?.trim()||'');$('#packageLabel').textContent=state.plan||'Pro';applyGuestFromUrl();updateCountdown();
}
function renderGallery(){const g=$('#photoGrid'),m=$('#galleryManager');g.innerHTML='';m.innerHTML='';(state.gallery||[]).forEach((src,i)=>{const img=new Image();img.src=src;img.alt='Galeri';g.append(img);const w=document.createElement('div');w.style.position='relative';const mi=img.cloneNode();w.append(mi);w.title='Klik untuk menghapus';w.onclick=()=>{state.gallery.splice(i,1);render();capture()};m.append(w)});if(!(state.gallery||[]).length){['Foto 1','Foto 2','Foto 3'].forEach(t=>{const d=document.createElement('div');d.className='photo-placeholder';d.textContent=t;g.append(d)})}}
async function saveInvitation(silent=false){if(!currentUser)return;if(!state.slug)state.slug=slugify(`${state.name1}-${state.name2}`);state.ownerId=state.ownerId||currentUser.id;state.ownerEmail=state.ownerEmail||currentUser.email;state.ownerName=state.ownerName||currentProfile?.name||'';const row=invitationToRow(state);let result;if(!currentInvitationId){result=await supabase.from('invitations').insert(row).select().single()}else result=await supabase.from('invitations').update({...row,updated_at:new Date().toISOString()}).eq('id',currentInvitationId).select().single();if(result.error){if(!silent)toast('Gagal menyimpan: '+friendlyError(result.error));return}currentInvitationId=result.data.id;state=invitationFromRow(result.data);$('#saveState').textContent='Tersimpan di Supabase';if(!silent)toast('Tersimpan ke Supabase');render()}
$('#saveCloud').onclick=()=>saveInvitation(false);$('#backDashboard').onclick=()=>showDashboard();$('#openInvitation').onclick=async()=>{if(!currentInvitationId)await saveInvitation(true);window.open(publicUrl(state,state.guestLinkName?.trim()||''),'_blank')};$('#copyShare').onclick=()=>navigator.clipboard.writeText($('#shareUrl').value).then(()=>toast('Link undangan disalin'));

$$('input:not([type=file]),textarea,select').forEach(el=>el.addEventListener('input',()=>{if(!$('#editorView').classList.contains('hidden'))capture()}));$$('input[type=checkbox]').forEach(el=>el.addEventListener('change',()=>{if(!$('#editorView').classList.contains('hidden'))capture()}));$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(`[data-panel="${btn.dataset.tab}"]`).classList.add('active')});$$('.template').forEach(btn=>btn.onclick=()=>{state.template=btn.dataset.template;$$('.template').forEach(x=>x.classList.remove('active'));btn.classList.add('active');capture()});$$('.view-switch button').forEach(btn=>btn.onclick=()=>{$$('.view-switch button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('#device').className='device '+btn.dataset.view});$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#scrollOpen').onclick=()=>$('#contentStart').scrollIntoView({behavior:'smooth'});$('#copyBank').onclick=()=>navigator.clipboard.writeText(state.bankNumber||'').then(()=>toast('Nomor rekening disalin'));$('#musicFab').onclick=async()=>{const a=$('#bgMusic');if(a.paused){try{await a.play();$('#musicFab').textContent='❚❚'}catch(e){toast('Klik lagi untuk memutar musik')}}else{a.pause();$('#musicFab').textContent='♫'}};

async function uploadFile(file,kind){if(!currentUser)throw new Error('Harus login');if(!currentInvitationId)await saveInvitation(true);const path=`${state.ownerId||currentUser.id}/invitations/${currentInvitationId}/${kind}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;$('#uploadProgress').classList.remove('hidden');$('#uploadProgress').textContent=`Upload ${kind}...`;const {error}=await supabase.storage.from(STORAGE_BUCKET).upload(path,file,{cacheControl:'3600',upsert:false});if(error){$('#uploadProgress').classList.add('hidden');throw error}const {data}=supabase.storage.from(STORAGE_BUCKET).getPublicUrl(path);$('#uploadProgress').classList.add('hidden');return data.publicUrl}
$('#coverUpload').onchange=async e=>{if(e.target.files[0]){state.cover=await uploadFile(e.target.files[0],'cover');render();await saveInvitation(true)}};$('#galleryUpload').onchange=async e=>{for(const f of [...e.target.files].slice(0,12)){state.gallery=state.gallery||[];state.gallery.push(await uploadFile(f,'gallery'))}render();await saveInvitation(true)};$('#qrisUpload').onchange=async e=>{if(e.target.files[0]){state.qris=await uploadFile(e.target.files[0],'qris');render();await saveInvitation(true)}};$('#musicUpload').onchange=async e=>{if(e.target.files[0]){state.music=await uploadFile(e.target.files[0],'music');render();await saveInvitation(true)}};

function stopGuestRealtime(){if(unsubscribeGuest){supabase.removeChannel(unsubscribeGuest);unsubscribeGuest=null}}
async function refreshGuestStats(){if(!currentInvitationId)return;const [r,g]=await Promise.all([supabase.from('rsvps').select('*').eq('invitation_id',currentInvitationId),supabase.from('guestbook').select('*').eq('invitation_id',currentInvitationId).order('created_at',{ascending:false})]);const rsvp=r.data||[];$('#rsvpYes').textContent=rsvp.filter(x=>x.status==='yes').reduce((n,x)=>n+(Number(x.pax)||1),0);$('#rsvpNo').textContent=rsvp.filter(x=>x.status==='no').length;$('#uniqueGuestCount').textContent=rsvp.length;$('#guestCount').textContent=(g.data||[]).length;renderGuestList(g.data||[]);$('#visitCount').textContent=Number(state.visitCount)||0}
function listenGuestStats(){if(!currentInvitationId)return;stopGuestRealtime();refreshGuestStats();unsubscribeGuest=supabase.channel('invite-'+currentInvitationId).on('postgres_changes',{event:'*',schema:'public',table:'rsvps',filter:`invitation_id=eq.${currentInvitationId}`},refreshGuestStats).on('postgres_changes',{event:'*',schema:'public',table:'guestbook',filter:`invitation_id=eq.${currentInvitationId}`},refreshGuestStats).subscribe()}
function renderGuestList(rows){const list=$('#guestList');list.innerHTML='';rows.slice(0,20).forEach(x=>{const i=document.createElement('div');i.className='guest-item';i.innerHTML=`<strong>${esc(x.name||'Tamu')}</strong><p>${esc(x.message||'')}</p>`;list.append(i)})}
$('#rsvpForm').onsubmit=async e=>{e.preventDefault();if(!currentInvitationId)return;try{const {error}=await supabase.from('rsvps').insert({invitation_id:currentInvitationId,name:$('#rsvpName').value.trim(),status:$('#rsvpStatus').value,pax:Number($('#rsvpPax').value)||1});if(error)throw error;toast('Konfirmasi kehadiran terkirim');$('#rsvpPax').value=1;refreshGuestStats()}catch(err){toast('RSVP gagal dikirim: '+friendlyError(err))}};
$('#guestbookForm').onsubmit=async e=>{e.preventDefault();if(!currentInvitationId)return;try{const {error}=await supabase.from('guestbook').insert({invitation_id:currentInvitationId,name:$('#guestbookName').value.trim(),message:$('#guestbookMessage').value.trim()});if(error)throw error;toast('Ucapan terkirim');$('#guestbookMessage').value='';refreshGuestStats()}catch(err){toast('Ucapan gagal dikirim: '+friendlyError(err))}};

async function loadPublicInvitation(idOrSlug){
 try{let q=supabase.from('invitations').select('*');const isUuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(idOrSlug);q=isUuid?q.eq('id',idOrSlug):q.eq('slug',idOrSlug);const {data,error}=await q.maybeSingle();if(error||!data)throw error||new Error('not-found');state=invitationFromRow(data);currentInvitationId=data.id;if(!state.published||!activeByDate(state)){document.body.innerHTML='<div class="inactive-notice"><div><h1>Undangan tidak aktif</h1><p>Undangan ini belum dipublikasikan atau masa aktifnya telah berakhir.</p></div></div>';return}document.body.classList.add('public-mode');showView('editorView');$('#sidebar').classList.add('hidden');$('.topbar').classList.add('hidden');$('.main-stage').style.margin='0';$('.preview-zone').style.padding='0';$('#device').className='device desktop';bindStateToInputs();render();recordVisit();const loadGuest=async()=>{const g=await supabase.from('guestbook').select('*').eq('invitation_id',currentInvitationId).order('created_at',{ascending:false});renderGuestList(g.data||[])};await loadGuest();unsubscribeGuest=supabase.channel('public-guest-'+currentInvitationId).on('postgres_changes',{event:'*',schema:'public',table:'guestbook',filter:`invitation_id=eq.${currentInvitationId}`},loadGuest).subscribe();if(state.music&&state.musicAutoplay){document.addEventListener('click',()=>$('#bgMusic').play().catch(()=>{}),{once:true})}
 }catch(e){document.body.innerHTML='<div class="inactive-notice"><div><h1>Undangan tidak ditemukan</h1><p>Periksa kembali link undangan yang Anda buka.</p></div></div>'}
}
async function recordVisit(){try{const sid=sessionStorage.getItem('adit_visit_'+currentInvitationId);if(sid)return;sessionStorage.setItem('adit_visit_'+currentInvitationId,'1');const {error}=await supabase.rpc('increment_invitation_visit',{p_invitation_id:currentInvitationId,p_guest:new URLSearchParams(location.search).get('to')||''});if(!error)state.visitCount=(Number(state.visitCount)||0)+1}catch(e){}}
function applyGuestFromUrl(){const to=new URLSearchParams(location.search).get('to');$('#pGuestName').textContent=to||'Bapak/Ibu/Saudara/i';if(to){$('#rsvpName').value=to;$('#guestbookName').value=to}}
function updateCountdown(){if(!state.eventDate)return;const target=new Date(`${state.eventDate}T${state.eventTime||'00:00'}:00`).getTime();let diff=Math.max(0,target-Date.now());const d=Math.floor(diff/86400000);diff%=86400000;const h=Math.floor(diff/3600000);diff%=3600000;const m=Math.floor(diff/60000),s=Math.floor((diff%60000)/1000);if($('#cdDays')){$('#cdDays').textContent=String(d).padStart(3,'0');$('#cdHours').textContent=String(h).padStart(2,'0');$('#cdMinutes').textContent=String(m).padStart(2,'0');$('#cdSeconds').textContent=String(s).padStart(2,'0')}}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function escapeAttr(s){return String(s||'').replace(/'/g,'%27')}
setInterval(updateCountdown,1000);boot();
